import './globals.css'
import { Inter } from 'next/font/google'
import Providers from './components/Providers'
import SigninButton from './components/SigninButton'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <Appbar /> */}
          <SigninButton/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
